#!/usr/bin/env python3

import biblib.bib
import biblib.messages
import argparse
import sys

def main():
    arg_parser = argparse.ArgumentParser(
        description='Flatten macros, combine, and pretty-print .bib database(s)')
    arg_parser.add_argument('bib', nargs='+', help='.bib file(s) to process',
                            type=open)
    arg_parser.add_argument('--resolve-crossrefs', action='store_true',
                            help='copy fields from cross-referenced entries')
    args = arg_parser.parse_args()

    try:
        # Load databases
        db = biblib.bib.Parser().parse(args.bib, log_fp=sys.stderr).get_entries()

        # Optionally resolve cross-references
        if args.resolve_crossrefs:
            db = biblib.bib.resolve_crossrefs(db)
    except biblib.messages.InputError:
        sys.exit(1)

    # Pretty-print entries
    for ent in db.values():
        print(ent.to_bib())
        print()

if __name__ == '__main__':
    main()
